version: "3.4"
services:
  frontend:
    build: ../client
    container_name: mymoviedbV2-frontend
    volumes:
      - ../client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8081:8080
    links:
      - app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "serve"] 
  app:
    build:
      context: ./
      dockerfile: dev.dockerfile
    container_name: mymoviedbV2-app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3333:3333
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - db
    command: ["npm", "run", "dev"]

  db:
    image: mysql:5.7
    container_name: mymoviedbV2-db
    environment:
      MYSQL_ROOT_PASSWORD: andre
      MYSQL_DATABASE: mymoviedbV2
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306

  admin:
    image: phpmyadmin/phpmyadmin
    container_name: mymoviedbV2-admin
    environment:
      PMA_PORT: "3306"
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: andre
    ports:
      - 8080:80
    links:
      - db
volumes:
  mysql:
